#coding=utf-8
"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import floor, ceil, sqrt

INIT = 1
RANGE = 1000000l #1e6

def triangle(n=1):
    return (1+n)*n/2

def nfactors(n):
    lim = long(ceil(sqrt(n)))
    nfac = 0
    for i in xrange(1, lim):
        if n % i == 0:
            nfac += 1

    return nfac*2

if __name__ == '__main__':
    i = 0
    for i in xrange(INIT, INIT+RANGE):
        tri = triangle(i)
        if  nfactors(tri) >= 500:
            print tri
            break
