"""Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?"""


LIMIT = 10**4


def calc_pentagon(n):
    return int(n * (3*n - 1) * 0.5)


def main():
    pentagon_list = [calc_pentagon(i) for i in xrange(1, LIMIT)]
    pentagon_set = set(pentagon_list)
    min_d = float('inf')
    for j in xrange(1, LIMIT):
        for k in xrange(j+1, LIMIT):
            pk = pentagon_list[k-1]
            pj = pentagon_list[j-1]
            d = pk - pj
            if (pk + pj) in pentagon_set and d in pentagon_set:
                min_d = d

    print(min_d)


if __name__ == '__main__':
    main()
