--[[
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
--]]


local function hexagonal(n)
    return n * (2*n - 1)
end


local function is_pentagonal(Pn)
    local n = (1 + math.sqrt(1 + 24*Pn)) / 6
    return math.floor(n) == n
end


local function is_triangular(Tn)
    local n = (-1 + math.sqrt(1 + 8*Tn)) / 2
    return math.floor(n) == n
end


local function main()
    local n = 143
    local hn
    repeat
        n = n + 1
        hn = hexagonal(n)
    until is_pentagonal(hn) and is_triangular(hn)
    print(hn)
end


main()
